#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle
##
##############################################################################

DIR="$(cd "$(dirname "$0")" && pwd)"

WRAPPER_JAR="$DIR/gradle/wrapper/gradle-wrapper.jar"

JAVA_CMD="java"

exec "$JAVA_CMD" -classpath "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
